import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/layout/Header";
import { CartProvider } from "@/features/cart/context/CartContext";
import { AuthProvider } from "@/features/auth/context/AuthContext";
import { getServerAuth } from "@/lib/auth";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const auth = await getServerAuth();

  return (
    <html lang="en">
      <body className={`antialiased`}>
        <AuthProvider initialUser={auth.user}>
          <CartProvider>
            <Header />
            {children}
          </CartProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
